Project setup
AnselemOdims/LeaderBoard pull request #1
Opened 2021-12-13 18:49 UTC by AnselemOdims

# Steps
- Created a new feature branch from the develop branch
- Initialized the node package manager
- Setup linters
- Installed webpack and set up its configuration file
- Built out the index page markup
- Added basic styling to the page
- Updated README.md file

# Screenshot

![image](https://user-images.githubusercontent.com/43995830/145869840-8df431fb-e602-4316-9fe7-5cc2fe714ab2.png)

2021-12-13 19:57 UTC, Dipeshtwis requested changes
Hi @AnselemOdims, 

:+1: This is good to make it this far, your project is really nice, congratulations on the good work you have done so far.

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


 ## Required Changes ♻️

**_Check the comments under the review_**

- [ ] I would recommend fixing the live demo link on the README. Currently, it's the link is broken.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

- N.A.

Cheers and Happy coding!👏👏👏
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**_Dipesh Kumar_**


------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project(check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-12-13 19:57 UTC, Dipeshtwis commented on src/style.css
> +}
- [ ] Make sure the design is the same as the original design.

### Original design
![Screenshot from 2021-12-14 01-14-32](https://user-images.githubusercontent.com/22434660/145877706-685bfa61-76ef-4cf4-846f-65d3058d3a10.png)


### Your design

![Screenshot from 2021-12-14 01-11-27](https://user-images.githubusercontent.com/22434660/145877642-d9e06c29-ecf1-4816-9463-ea6b01a856fb.png)

2021-12-14 05:21 UTC, AnselemOdims commented on src/style.css
> +}
Thank you for the feedback @Dipeshtwis. I only left it that way because the instructions said we should only apply basic styling for now.

2021-12-14 05:55 UTC, omar-labana commented
Hi @AnselemOdims, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-12-14 06:26 UTC, merged